package storage

import (
	"database/sql"
	"fmt"

	_ "modernc.org/sqlite"
)

// DB wraps sql.DB — our single database connection pool.
type DB struct {
	conn *sql.DB
}

// New opens the database at the given path and runs migrations.
func New(path string) (*DB, error) {
	conn, err := sql.Open("sqlite", path)
	if err != nil {
		return nil, fmt.Errorf("open db: %w", err)
	}

	// Ping forces an actual connection — we want to fail fast at startup
	if err := conn.Ping(); err != nil {
		return nil, fmt.Errorf("ping db: %w", err)
	}

	db := &DB{conn: conn}

	// run migrations immediately after connecting
	if err := db.migrate(); err != nil {
		return nil, fmt.Errorf("migrate: %w", err)
	}

	return db, nil
}

// migrate creates all tables if they don't exist.
// it's idempotent, it won't fail or duplicate data on a second run.
func (db *DB) migrate() error {
	query := `
	CREATE TABLE IF NOT EXISTS vehicles (
		id       TEXT PRIMARY KEY,    -- uuid, generated by the service layer
		name     TEXT NOT NULL,
		status   TEXT NOT NULL,
		capacity INTEGER NOT NULL
	);`

	if _, err := db.conn.Exec(query); err != nil {
		return fmt.Errorf("create vehicles table: %w", err)
	}

	return nil
}

// Close releases the connection pool.
func (db *DB) Close() error {
	return db.conn.Close()
}
